# -----------------------------------------------------------------------------
# Dracula skin
# -----------------------------------------------------------------------------

# Styles...
foreground: &foreground "#cad3f5" # text
background: &background "default"
current_line: &current_line "#363a4f" # surface 0
selection: &selection "#F4DBD6"
comment: &comment "#6e738d" # overlay 0
cyan: &cyan "#91d7e3" # sky
green: &green "#a6da95"
orange: &orange "#ffb86c"
pink: &pink "#f5bde6"
purple: &purple "#c6a0f6"
red: &red "#ed8796"
yellow: &yellow "#eed49f"

# Skin...
k9s:
  # General K9s styles
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *purple
  # Command prompt styles
  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *purple
  # ClusterInfoView styles.
  info:
    fgColor: *pink
    sectionColor: *foreground
  # Dialog styles.
  dialog:
    fgColor: *foreground
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *purple
    buttonFocusFgColor: *yellow
    buttonFocusBgColor: *pink
    labelFgColor: *orange
    fieldFgColor: *foreground
  frame:
    # Borders styles.
    border:
      fgColor: *selection
      focusColor: *current_line
    menu:
      fgColor: *foreground
      keyColor: *pink
      # Used for favorite namespaces
      numKeyColor: *pink
    # CrumbView attributes for history navigation.
    crumbs:
      fgColor: *foreground
      bgColor: *current_line
      activeColor: *current_line
    # Resource status and update styles
    status:
      newColor: *cyan
      modifyColor: *purple
      addColor: *green
      errorColor: *red
      highlightColor: *orange
      killColor: *comment
      completedColor: *comment
    # Border title styles.
    title:
      fgColor: *foreground
      bgColor: *current_line
      highlightColor: *orange
      counterColor: *purple
      filterColor: *pink
  views:
    # Charts skins...
    charts:
      bgColor: default
      defaultDialColors:
        - *purple
        - *red
      defaultChartColors:
        - *purple
        - *red
    # TableView attributes.
    table:
      fgColor: *foreground
      bgColor: *background
      # Header row styles.
      header:
        fgColor: *foreground
        bgColor: *background
        sorterColor: *cyan
    # Xray view attributes.
    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *current_line
      graphicColor: *purple
      showIcons: false
    # YAML info styles.
    yaml:
      keyColor: *pink
      colonColor: *purple
      valueColor: *foreground
    # Logs styles.
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *foreground
        bgColor: *purple
        toggleOnColor: *green
        toggleOffColor: *cyan
