#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
ICON_FONT="JetBrainsMono Nerd Font"

SHADOW=on

# Setting up the general bar appearance and default values
sketchybar --bar     height=36                                           \
                     corner_radius=9                                     \
                     border_width=0                                      \
                     margin=10                                            \
                     blur_radius=36                                      \
                     position=top                                        \
                     padding_left=8                                     \
                     padding_right=8                                    \
                     color=$BAR_COLOR                                    \
                     topmost=off                                         \
                     sticky=on                                           \
                     font_smoothing=on                                  \
                     y_offset=8                                          \
                     shadow=$SHADOW                                      \
                     notch_width=200                                     \
                                                                         \
           --default drawing=on                                          \
                     updates=when_shown                                  \
                     label.font="$FONT:Regular:12.0"                     \
                     icon.font="$ICON_FONT:Regular:14.0"                 \
                     icon.color=$ICON_COLOR                              \
                     label.color=$LABEL_COLOR                            \
                     icon.padding_left=$PADDINGS                         \
                     icon.padding_right=$PADDINGS                        \
                     label.padding_left=$PADDINGS                        \
                     label.padding_right=$PADDINGS                       \
                     background.padding_right=$PADDINGS                  \
                     background.padding_left=$PADDINGS                   \
                     popup.background.border_width=$POPUP_BORDER_WIDTH   \
                     popup.background.corner_radius=$POPUP_CORNER_RADIUS \
                     popup.background.border_color=$POPUP_BORDER_COLOR   \
                     popup.background.color=$POPUP_BACKGROUND_COLOR      \
                     popup.background.shadow.drawing=$SHADOW

# Left
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/calendar.sh"

sketchybar --add alias "Control Center,WiFi" right
sketchybar --add alias "Control Center,Battery" right

source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/bluetooth.sh"

############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."
